# Generated by Django 3.1.5 on 2021-01-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210105_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('author_email', models.EmailField(max_length=254)),
                ('review_title', models.CharField(max_length=300, null=True)),
                ('review_body', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('sentiment_score', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
